on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build Docker Image
      run: docker build -t docker/multinet:${{ github.sha }} -t docker/multinet:${{ github.ref_name }} -t ${{ secrets.DOCKERHUB_USERNAME }}/multinet:${{ github.ref_name }} .
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Publish to DockerHub
      run: docker push docker/multinet:${{ github.sha }}