name: Build and Publish Docker Image

# Required Since Release Creation in GitHub (itself) doesn't create a push (not remote)
on:
  release:
    types:
    - created

jobs:
  push_to_registry:
    name: Build and publish
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: "Set current date as env variable"
      run: |
        echo "builddate=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      id: dateversion
    - name: Build Docker Image
      run: docker build -t felsokning/multinet:${{ github.sha }} .
    - name: Tag Docker Image (Git Tag)
      run: docker tag felsokning/multinet:${{ github.sha }} felsokning/multinet:${{ github.ref_name }}
    - name: Tag Docker Image (Date)
      run: docker tag felsokning/multinet:${{ github.sha }} felsokning/multinet:${{ steps.dateversion.outputs.builddate }}
    - name: Tag Docker Image (latest)
      run: docker tag felsokning/multinet:${{ github.sha }} felsokning/multinet:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: felsokning
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Publish to DockerHub
      run: docker push felsokning/multinet:${{ github.ref_name }}