name: Build and Publish Docker Image

# Required Since Release Creation in GitHub (itself) doesn't create a push (not remote)
on:
  release:
    types:
    - created

jobs:
  push_to_registry:
    name: Build and publish
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build Docker Image
      run: docker build -t docker/felsokning/multinet:${{ github.sha }} -t docker/felsokning/multinet:${{ github.ref_name }} -t felsokning/multinet:${{ github.ref_name }} .
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: felsokning
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Publish to DockerHub
      run: docker push docker/felsokning/multinet:${{ github.sha }}